services:
  server:
    image: caddy:2.10-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server/local.Caddyfile:/etc/caddy/Caddyfile
    networks:
      - doc-manager

  database:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - doc-manager

  db-admin:
    image: dpage/pgadmin4:9.8.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./db-admin:/var/lib/pgadmin
    networks:
      - doc-manager

  api:
    restart: always
    build:
      context: ./backend/doc-manager
      dockerfile: local.Dockerfile
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./backend/doc-manager:/app
    ports:
      - 8001:8001
    networks:
      - doc-manager

  www:
    restart: always
    build:
      context: ./frontend/doc-manager
      dockerfile: local.Dockerfile
    volumes:
      - ./frontend/doc-manager:/app
    networks:
      - doc-manager

volumes:
  database:
  db-admin:

networks:
  doc-manager:
